### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'new_context' after update to 0.0.11 version

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-python#458]
Hi!
I use following versions
```
playwright==1.8.0a1
pytest-playwright==0.0.11
```
When I try to run this simple test
```
import pytest

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "viewport": {
            "width": 1920,
            "height": 1080,
        }
    }


def test_3(page):
    page.goto("https://github.com/")
 ```
 I see the following errors
 ```
 
test_3.py::test_3 ERROR                                                                                                      [100%]
test_3.py::test_3 ERROR                                                                                                      [100%]

============================================================== ERRORS ==============================================================
_____________________________________________________ ERROR at setup of test_3 _____________________________________________________

browser = <selenium.webdriver.chrome.webdriver.WebDriver (session="a04299d9467e720629597b732e376de3")>
browser_context_args = {'viewport': {'height': 1080, 'width': 1920}}

    @pytest.fixture
    def context(
        browser: Browser, browser_context_args: Dict
    ) -> Generator[BrowserContext, None, None]:
>       context = browser.new_context(**browser_context_args)
E       AttributeError: 'WebDriver' object has no attribute 'new_context'

../../.venv/lib/python3.9/site-packages/pytest_playwright/pytest_playwright.py:128: AttributeError
------------------------------------------------------ Captured stdout setup -------------------------------------------------------
['--start-maximized', 'window-size=2560,1440']
___________________________________________________ ERROR at teardown of test_3 ____________________________________________________

request = <SubRequest 'browser' for <Function test_3>>

    @pytest.fixture()
    def browser(request):
        browser = None
        options = get_browser_options(request)
        # check, if we try to pass arguments
        if hasattr(request, 'param'):
            # parse param
            params = request.param.split(", ")
            print(params)
            if params[0] == "experimenatal_option":
                print(params[1], params[2], params[3])
                options.add_experimental_option(params[1], {params[2]: params[3]})
        # options.add_experimental_option("w3c", False)
        # add for allowing to see network logs
        caps = DesiredCapabilities.CHROME
        #as per latest docs
        caps['goog:loggingPrefs'] = {'performance': 'ALL'}
        browser = webdriver.Chrome(desired_capabilities=caps, options=options)
        browser.implicitly_wait(5)
        yield browser
        # Do teardown (this code will be executed after each test):
        #print(request.node.rep_call)
        # to do - if broken, pls make a screenshot
>       if request.node.rep_call.failed:
E       AttributeError: 'Function' object has no attribute 'rep_call'

../../config/init_browser.py:55: AttributeError
------------------------------------------------------ Captured stdout setup -------------------------------------------------------
['--start-maximized', 'window-size=2560,1440']
===================================================== short test summary info ======================================================
ERROR test_3.py::test_3 - AttributeError: 'WebDriver' object has no attribute 'new_context'
ERROR test_3.py::test_3 - AttributeError: 'Function' object has no attribute 'rep_call'
```

**Comment by Louis24** [comment]
me too
