### ISSUE TITLE
Not work with celery

### ISSUE THREAD

**Issue by yswtrue** [microsoft/playwright-python#399]
this is the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 35, in run
    return task._orig_run(*args, **kwargs)
  File "/app/seatower_analytics/tiktok/tasks.py", line 68, in update_tiktok_user
    api = TikTokApi.get_instance(
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 89, in get_instance
    TikTokApi(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 56, in __init__
    self.browser = browser(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/browser.py", line 82, in __init__
    raise e
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/browser.py", line 78, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/browser.py", line 26, in get_playwright
    raise e
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/browser.py", line 24, in get_playwright
    playwright = sync_playwright().start()
  File "/usr/local/lib/python3.8/site-packages/playwright/_main.py", line 84, in start
    return self.__enter__()
  File "/usr/local/lib/python3.8/site-packages/playwright/_main.py", line 78, in __enter__
    dispatcher_fiber.switch()
  File "/usr/local/lib/python3.8/site-packages/playwright/_main.py", line 59, in greenlet_main
    loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/playwright/_connection.py", line 134, in run_as_sync
    await self.run()
  File "/usr/local/lib/python3.8/site-packages/playwright/_connection.py", line 139, in run
    await self._transport.run()
  File "/usr/local/lib/python3.8/site-packages/playwright/_transport.py", line 39, in run
    proc = await asyncio.create_subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 190, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "/usr/local/lib/python3.8/subprocess.py", line 804, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/lib/python3.8/subprocess.py", line 1504, in _get_handles
    errwrite = stderr.fileno()
AttributeError: 'LoggingProxy' object has no attribute 'fileno'

```

**Comment by mxschmitt** [comment]
Original bug report #246
Probably caused by #318

**Comment by pavelfeldman** [comment]
https://github.com/celery/celery/issues/928
